version: '3'
services: 
  mydb:
    image: mysql:latest
    container_name: mydb
    ports: 
      - "3306:3306"
    volumes: 
      - ./mysql/data:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=123456
    command:  --default-authentication-plugin=mysql_native_password #支持远程访问
    networks: 
      - lnmp
  
  myredis: 
    image: redis:6
    container_name: myredis
    ports: 
      - "6379:6379"
    volumes: 
      - ./redis/data:/data
    networks: 
      - lnmp

  myphp:
    image: php7-fpm:v1.0
    container_name: myphp
    ports: 
      - "9000:9000"
    volumes: 
      # - ~/dockerPro/www:/var/www/html
      - ~/dockerPro/www:/www
      - ./phpfpm/etc:/usr/local/etc
    links: 
      - mydb:mydb
      - myredis:myredis
    networks: 
      - lnmp
      
  mynginx:
    image: nginx:latest
    container_name: mynginx
    ports: 
      - "80:80"
    volumes: 
      - ~/dockerPro/www:/www
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    links: 
      - myphp:PHP-FPM 
    networks: 
      - lnmp
   
networks: 
  lnmp:
    driver: bridge

    


    


  




  



























    

    










